export const ROLE_OPTIONS = [
  "All",
  "Data Engineer",
  "Data Analyst",
  "Data Scientist",
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "DevOps Engineer",
  "Product Manager",
  "Project Manager",
  "UX/UI Designer",
  "Business Analyst",
  "Machine Learning Engineer",
  "Cloud Engineer",
  "Mobile Developer",
  "Other",
];
